name: LunchTime
on:
   pull_request:
    types: [closed] 
   workflow_dispatch:
    
env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: alstol/Self-Reward-Actions@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       IMAGE_URL: https://media1.tenor.com/images/1af4a7934b03fbe450eef4cac27e7fda/tenor.gif
       MEME_HEADER: <NAME> just merged his own PR! Shame!!
       
    - uses: GoldenspearLLC/slack-chat-postmessage@v3
      with:
       channel: '#lunchtime'
       text: "@here <NAME> just merged his own PR on https://github.com/Adrian-testorg/lunchtime#${{ github.head_ref }}"
    
    - uses: GoldenspearLLC/slack-chat-postmessage@v3
      with:
       channel: '#lunchtime'
       text: "<!here> I merged my own PR. I'm going to buy everyone lunch tomorrow. :pizza: for pizza :sushi: for sushi :beer: for pub food :coffee: for cafe"

